# These are supported funding model platforms

github: eliasempresas eliasempresasBOT # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: eliasempresas # Replace with a single Patreon username
open_collective: eliasempresas # Replace with a single Open Collective username
ko_fi: eliasempresas # Replace with a single Ko-fi username
tidelift: eliasempresas # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: eliasempresas # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: eliasempresas # Replace with a single Liberapay username
issuehunt: eliasempresas # Replace with a single IssueHunt username
lfx_crowdfunding: eliasempresas # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: eliasempresas # Replace with a single Polar username
buy_me_a_coffee: eliasempresas # Replace with a single Buy Me a Coffee username
thanks_dev: eliasempresas # Replace with a single thanks.dev username
custom: https://www.eliasempresas.com/doar # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
